In [7]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

In [8]:
tensor1= torch.rand(3,3,3)
tensor2= torch.rand(3,3,3)

In [9]:
tensor1+tensor2

tensor([[[0.8935, 0.8317, 0.9787],
         [1.1256, 0.8251, 1.0049],
         [0.6858, 1.0775, 0.7802]],

        [[1.1621, 1.5275, 1.0325],
         [0.9779, 0.1262, 1.3098],
         [1.0256, 0.6955, 0.2682]],

        [[0.2104, 1.3873, 1.1143],
         [0.2572, 1.5747, 1.2221],
         [1.8441, 0.1964, 1.7887]]])

In [15]:
tensor= torch.rand(2,3,2,4)
tensor

tensor([[[[0.6230, 0.8644, 0.7305, 0.3618],
          [0.2624, 0.1560, 0.5757, 0.0205]],

         [[0.4029, 0.4536, 0.0541, 0.4737],
          [0.8773, 0.3539, 0.3388, 0.3682]],

         [[0.0222, 0.1535, 0.9638, 0.3663],
          [0.4470, 0.1850, 0.9394, 0.9951]]],


        [[[0.1652, 0.2978, 0.2319, 0.5279],
          [0.5613, 0.9012, 0.3340, 0.5727]],

         [[0.0303, 0.7578, 0.2671, 0.8766],
          [0.0475, 0.7439, 0.2307, 0.8837]],

         [[0.0254, 0.2139, 0.1204, 0.7271],
          [0.8961, 0.3522, 0.8385, 0.1140]]]])

In [18]:
tensor[0,1]

tensor([[0.4029, 0.4536, 0.0541, 0.4737],
        [0.8773, 0.3539, 0.3388, 0.3682]])

In [20]:

tensor= torch.rand(3,30)
tensor

tensor([[0.9408, 0.6506, 0.0695, 0.1957, 0.4247, 0.3393, 0.7344, 0.8683, 0.2140,
         0.6970, 0.5284, 0.9440, 0.2913, 0.2505, 0.6381, 0.5787, 0.9371, 0.3934,
         0.2494, 0.0693, 0.0481, 0.0055, 0.5034, 0.0300, 0.9457, 0.2231, 0.2218,
         0.3080, 0.9058, 0.0887],
        [0.1617, 0.2250, 0.6832, 0.4990, 0.6102, 0.7636, 0.9955, 0.2300, 0.4538,
         0.7271, 0.4757, 0.0886, 0.6580, 0.0116, 0.4297, 0.5792, 0.9041, 0.7810,
         0.6170, 0.8802, 0.5141, 0.9174, 0.7329, 0.3845, 0.4624, 0.2090, 0.3391,
         0.1609, 0.8340, 0.5204],
        [0.9256, 0.3642, 0.0734, 0.5502, 0.1087, 0.5990, 0.1373, 0.2614, 0.6131,
         0.7533, 0.7101, 0.8556, 0.1098, 0.2539, 0.2466, 0.7263, 0.2672, 0.9849,
         0.9459, 0.1434, 0.6663, 0.9021, 0.7984, 0.2756, 0.8039, 0.7084, 0.1959,
         0.8237, 0.2567, 0.8763]])

In [21]:
tensor.flatten()

tensor([0.9408, 0.6506, 0.0695, 0.1957, 0.4247, 0.3393, 0.7344, 0.8683, 0.2140,
        0.6970, 0.5284, 0.9440, 0.2913, 0.2505, 0.6381, 0.5787, 0.9371, 0.3934,
        0.2494, 0.0693, 0.0481, 0.0055, 0.5034, 0.0300, 0.9457, 0.2231, 0.2218,
        0.3080, 0.9058, 0.0887, 0.1617, 0.2250, 0.6832, 0.4990, 0.6102, 0.7636,
        0.9955, 0.2300, 0.4538, 0.7271, 0.4757, 0.0886, 0.6580, 0.0116, 0.4297,
        0.5792, 0.9041, 0.7810, 0.6170, 0.8802, 0.5141, 0.9174, 0.7329, 0.3845,
        0.4624, 0.2090, 0.3391, 0.1609, 0.8340, 0.5204, 0.9256, 0.3642, 0.0734,
        0.5502, 0.1087, 0.5990, 0.1373, 0.2614, 0.6131, 0.7533, 0.7101, 0.8556,
        0.1098, 0.2539, 0.2466, 0.7263, 0.2672, 0.9849, 0.9459, 0.1434, 0.6663,
        0.9021, 0.7984, 0.2756, 0.8039, 0.7084, 0.1959, 0.8237, 0.2567, 0.8763])

In [22]:
tensor.reshape(10,-1)

tensor([[0.9408, 0.6506, 0.0695, 0.1957, 0.4247, 0.3393, 0.7344, 0.8683, 0.2140],
        [0.6970, 0.5284, 0.9440, 0.2913, 0.2505, 0.6381, 0.5787, 0.9371, 0.3934],
        [0.2494, 0.0693, 0.0481, 0.0055, 0.5034, 0.0300, 0.9457, 0.2231, 0.2218],
        [0.3080, 0.9058, 0.0887, 0.1617, 0.2250, 0.6832, 0.4990, 0.6102, 0.7636],
        [0.9955, 0.2300, 0.4538, 0.7271, 0.4757, 0.0886, 0.6580, 0.0116, 0.4297],
        [0.5792, 0.9041, 0.7810, 0.6170, 0.8802, 0.5141, 0.9174, 0.7329, 0.3845],
        [0.4624, 0.2090, 0.3391, 0.1609, 0.8340, 0.5204, 0.9256, 0.3642, 0.0734],
        [0.5502, 0.1087, 0.5990, 0.1373, 0.2614, 0.6131, 0.7533, 0.7101, 0.8556],
        [0.1098, 0.2539, 0.2466, 0.7263, 0.2672, 0.9849, 0.9459, 0.1434, 0.6663],
        [0.9021, 0.7984, 0.2756, 0.8039, 0.7084, 0.1959, 0.8237, 0.2567, 0.8763]])

In [24]:
tensor1= torch.rand(1,4,3,1)
tensor2= torch.rand(3,4,1,4)
# broadcasating

tensor1+tensor2


tensor([[[[1.4168, 0.9766, 1.3219, 1.3196],
          [1.7549, 1.3148, 1.6600, 1.6577],
          [1.3999, 0.9597, 1.3050, 1.3027]],

         [[1.0421, 0.9236, 0.5401, 0.6241],
          [1.4365, 1.3180, 0.9344, 1.0185],
          [1.4937, 1.3751, 0.9916, 1.0756]],

         [[0.9879, 1.0395, 0.8056, 0.6086],
          [1.2529, 1.3045, 1.0706, 0.8736],
          [1.0939, 1.1454, 0.9116, 0.7146]],

         [[0.8904, 1.2281, 0.8694, 1.2007],
          [0.2870, 0.6248, 0.2660, 0.5973],
          [0.7450, 1.0827, 0.7240, 1.0553]]],


        [[[1.4888, 1.2520, 1.3992, 0.9866],
          [1.8269, 1.5902, 1.7373, 1.3247],
          [1.4719, 1.2352, 1.3823, 0.9697]],

         [[0.4273, 0.2882, 0.3592, 0.5279],
          [0.8216, 0.6825, 0.7535, 0.9222],
          [0.8788, 0.7397, 0.8107, 0.9794]],

         [[1.2717, 1.3408, 0.8665, 0.4945],
          [1.5367, 1.6058, 1.1315, 0.7595],
          [1.3776, 1.4468, 0.9725, 0.6005]],

         [[1.1871, 1.6549, 1.7331, 0.9132],
          [0.583